import SMBL
include: SMBL.include

USE_HOME=1

#include: a

rule all:
        input:
                PROG_DWGSIM,
                PROG_BWA,
                FA_EXAMPLE
        params:
                PREF="simulated_reads",
                INDEX="bwa_index"
        output:
                "alignment.sam"
        run:
                shell("{input[0]} -C 1 {input[2]} {params.PREF}")
                shell("{input[1]} index {input[2]}")
                shell("{input[1]} mem {input[2]} {params.PREF}.bfast.fastq > alignment.sam")


