import smbl
include: smbl.include()

rule all:
        input:
                smbl.prog.DWGSIM,
                smbl.prog.BWA,
                smbl.fasta.EXAMPLE
        params:
                PREF="simulated_reads",
                INDEX="bwa_index"
        output:
                "alignment.sam"
        run:
                shell("{input[0]} -C 1 {input[2]} {params.PREF}")
                shell("{input[1]} index {input[2]}")
                shell("{input[1]} mem {input[2]} {params.PREF}.bfast.fastq > alignment.sam")


